### ISSUE TITLE
How to get only modified fields 

### ISSUE THREAD

**Issue by praneeththota** [ivmarcos/sequelize-version#10]
How can I get only the modified changes between versions. Is there any method to get only changed fields for the particular version ?

**Comment by ivmarcos** [comment]
Hi @praneeththota, you can achieve that by using a diff function and iterating the version set and comparing each with the latest version to get the changes. I've created an example below that I hope will help clarify.

```js
//using deep-diff just for example
import diff from 'deep-diff';

const lastVersion = await PersonVersion.findOne({where : {id: 1}, order: [['version_id', 'desc']], raw: true});
const allVersions = await PersonVersion.findAll({where: {id: 1}, raw: true});

const differences = allVersions.map(version => diff(lastVersion, version));
```

**Comment by ivmarcos** [comment]
This library is intended to maintain a faithful copy of the entity and therefore does not provide a direct way to create additional fields. Although you can create this field `user_id` or something like `updatedBy_id` (I imagine you want to trace the user who made an update) in the origin model and so the user will also be persisted in the version table. Related to https://github.com/ivmarcos/sequelize-version/issues/7.
