### ISSUE TITLE
Add AfterBulkDestroy hook

### ISSUE THREAD

**Issue by sumac13** [ivmarcos/sequelize-version#14]
Is it possible to add a hook for bulk destroys, we have cases where we need to check the history of objects which may have been deleted in a bulk transaction.

**Comment by ivmarcos** [comment]
Hi there @sumac13 ! Which sequelize version are you using? Please try setting the individualHooks flag in the options, for instance ```Model.destroy({ where: {accessLevel: 0}, individualHooks: true})```

**Comment by sumac13** [comment]
Thanks @ivmarcos I've added the individualHooks flag and this is working for us now, appreciate the quick reply.
