### ISSUE TITLE
User tracking and/or custom revision fields

### ISSUE THREAD

**Issue by MicroDroid** [ivmarcos/sequelize-version#7]
I need to track which user has made a certain revision. It should be as simple as adding an extra field in the revisions table.

**Comment by ivmarcos** [comment]
Hi @MicroDroid! You can track any changes as long the fields are in the origin model, including associations. In this case, I would suggest you to create a user field in the origin model or make an association with the user model, if there's one. 

```javascript
//using field 
const ModelWithUserField = sequelize.define('ModelWithUserField', {
id: {
//...field attributes
},
userId: {
//...field attributes
}, 
//...model options)
```
or

```javascript
ModelWithUserField.belongsTo(UserModel);
```

**Comment by MicroDroid** [comment]
@ivmarcos By what I said above I mean the author who created the *edit*, not the actual *model.*

Owner of an entity != Whoever edited the entity

**Comment by ivmarcos** [comment]
What I meant with the suggestion is that you would have to set the user when the change is made.  It's how I do, by the way.

```javascript
//define models
const Model = sequelize.define(...);
const UserModel = sequelize.define(...);
Model.belongsTo(UserModel);
const VersionModel = new Version(Model);

const user = await UserModel.findById(1);
const model = await Model.findById(1);

//make some changes
model.name = 'Marcos';
model.setUser(user); //or something like setUpdateByUser 

await model.save();

const userRevisions = await Model.getVersions({where: {userId: user.id}});
//or
const userRevisions = await VersionModel.findAll({where: {userId: user.id}});
```

**Comment by MicroDroid** [comment]
@ivmarcos But making an edit to the entity doesn't automatically imply ownership. Thus, changing the `user_id` field in the original model makes no sense.

Unless I am again missing the point of what you're saying :thinking:

**Comment by ivmarcos** [comment]
@MicroDroid, I was thinking that you wanted to track changes of data made by an user, so do you mean to know when an user created an entity in db? That's what you mean to ownership?

**Comment by MicroDroid** [comment]
@ivmarcos I want to track both. `user_id` should be a persistent, never changing, field in the entity that refers to the user who *created* the entity.

While there should be some other `user_id` in the *revision model* that refers to whoever made the edit.

**Comment by ivmarcos** [comment]
Sorry, I get it now. In these cases I use both fields in original model, something like **createdByUser** and **updatedByUser**, createdByUser remaining always with the same value and both are persisted in revision table. This concept is similar to what happens with the very often used fields **createdAt** and **updateAt**.

**Comment by MicroDroid** [comment]
But that is not an ideal solution. The ideal solution is to put the updatedByUser field in the revision model itself.

**Comment by ivmarcos** [comment]
Maybe it's not an ideal solution for you, but it makes sense to me. How do you plan to set user data only for the version instance? Despite that, I was intending a time ago to create a function that allows complete customization for the version models attributes. Something like:

```javascript

const options = {
  versionAttributes: (options) => {
    return {
      //version attrs
    }
  }
}
```

If this works for you, let me know okay.

**Comment by ivmarcos** [comment]
closed due to lack of response
